-- # 1
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) AS 'count'
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
HAVING ANIMAL_TYPE = 'Dog' OR ANIMAL_TYPE = 'Cat'
ORDER BY ANIMAL_TYPE

-- # 2
SELECT NAME, COUNT(NAME) AS 'count'
FROM ANIMAL_INS
GROUP BY NAME
HAVING count >= 2

-- # 3
SELECT HOUR(DATETIME) AS 'HOUR', COUNT(DATETIME) AS 'COUNT'
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR >=9 AND HOUR<20
ORDER BY HOUR

-- # 4
SET @hour = -1;
SELECT
    (@hour := @hour + 1) AS 'HOUR',
    (SELECT COUNT(*) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) = @HOUR) AS 'COUNT'
FROM ANIMAL_OUTS
WHERE @hour < 23