-- # 1
SELECT MAX(DATETIME) AS '시간'
FROM ANIMAL_INS;

-- # 2
SELECT MIN(DATETIME) AS '시간'
FROM ANIMAL_INS;

-- # 3
SELECT COUNT(ANIMAL_ID) AS 'count'
FROM ANIMAL_INS;

-- # 4
SELECT COUNT(DISTINCT NAME) AS 'count'
FROM ANIMAL_INS